### PR TITLE
Issue #473: Fix postprocessing bug associated with time steps that are not days

### LINKED ISSUE #473: `enw_nowcast_samples()` and `enw_nowcast_summary()` give unexpected output when not working with daily time steps
These two postprocessing functions appear to have a bug in which the time step is not accounted for when selecting rows by reference date, causing certain rows to be repeated in the output when the time steps are not days.

**To Reproduce**
1. Run the code in [`germany_weekly_process_model.R`](https://github.com/epinowcast/epinowcast/blob/main/inst/examples/germany_weekly_process_model.R)
2. Run:

```{r}
enw_nowcast_summary(
  nowcast$fit[[1]],
  nowcast$latest[[1]],
  timestep = "week"
  )

enw_nowcast_samples(
  nowcast$fit[[1]],
  nowcast$latest[[1]],
  timestep = "week"
)
```

The actual output is 

```{r}
   reference_date report_date .group max_confirm location age_group confirm cum_prop_reported delay prop_reported     mean median        sd      mad
           <IDat>      <IDat>  <num>       <int>   <fctr>    <fctr>   <int>             <num> <num>         <num>    <num>  <num>     <num>    <num>
1:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1 1073.000   1073   0.00000   0.0000
2:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1 1759.981   1758  13.22019  11.8608
3:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1 2378.443   2373  40.30066  35.5824
4:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1 2816.300   2805 133.55074 127.5036
5:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1 3881.254   3788 796.09969 744.2652
        q5    q20     q35   q50    q65    q80     q95      rhat  ess_bulk ess_tail
     <num>  <num>   <num> <num>  <num>  <num>   <num>     <num>     <num>    <num>
1: 1073.00 1073.0 1073.00  1073 1073.0 1073.0 1073.00        NA        NA       NA
2: 1743.00 1749.0 1753.00  1758 1763.0 1769.0 1782.00 1.0021788  983.9456 823.6433
3: 2323.00 2345.0 2360.00  2373 2389.0 2409.0 2449.00 0.9986244 1014.0755 781.9780
4: 2628.00 2703.8 2758.65  2805 2851.0 2911.4 3062.05 1.0018928  826.8875 778.1008
5: 2791.55 3207.8 3489.65  3788 4111.7 4486.4 5356.10 1.0024478  919.1985 985.5503
```

```{r}
reference_date report_date .group max_confirm location age_group confirm cum_prop_reported delay prop_reported .chain .iteration .draw sample
              <IDat>      <IDat>  <num>       <int>   <fctr>    <fctr>   <int>             <num> <num>         <num>  <int>      <int> <int>  <num>
   1:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      1          1     1   1073
   2:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      1          2     2   1073
   3:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      1          3     3   1073
   4:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      1          4     4   1073
   5:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      1          5     5   1073
  ---                                                                                                                                              
4996:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      2        496   996   3965
4997:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      2        497   997   4088
4998:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      2        498   998   3227
4999:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      2        499   999   3289
5000:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0             1      2        500  1000   3982
```

Where we would have expected instead something like:

```{r}
   reference_date report_date .group max_confirm location age_group confirm cum_prop_reported delay prop_reported     mean median        sd      mad
           <IDat>      <IDat>  <num>       <int>   <fctr>    <fctr>   <int>             <num> <num>         <num>    <num>  <num>     <num>    <num>
1:     2021-08-11  2021-09-08      1        1073       DE       00+    1073                 1     4    0.01863933 1073.000   1073   0.00000   0.0000
2:     2021-08-18  2021-09-08      1        1733       DE       00+    1733                 1     3    0.03058280 1759.981   1758  13.22019  11.8608
3:     2021-08-25  2021-09-08      1        2268       DE       00+    2268                 1     2    0.11463845 2378.443   2373  40.30066  35.5824
4:     2021-09-01  2021-09-08      1        2388       DE       00+    2388                 1     1    0.36934673 2816.300   2805 133.55074 127.5036
5:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0    1.00000000 3881.254   3788 796.09969 744.2652
        q5    q20     q35   q50    q65    q80     q95      rhat  ess_bulk ess_tail
     <num>  <num>   <num> <num>  <num>  <num>   <num>     <num>     <num>    <num>
1: 1073.00 1073.0 1073.00  1073 1073.0 1073.0 1073.00        NA        NA       NA
2: 1743.00 1749.0 1753.00  1758 1763.0 1769.0 1782.00 1.0021788  983.9456 823.6433
3: 2323.00 2345.0 2360.00  2373 2389.0 2409.0 2449.00 0.9986244 1014.0755 781.9780
4: 2628.00 2703.8 2758.65  2805 2851.0 2911.4 3062.05 1.0018928  826.8875 778.1008
5: 2791.55 3207.8 3489.65  3788 4111.7 4486.4 5356.10 1.0024478  919.1985 985.5503

```{r}
      reference_date report_date .group max_confirm location age_group confirm cum_prop_reported delay prop_reported .chain .iteration .draw sample
              <IDat>      <IDat>  <num>       <int>   <fctr>    <fctr>   <int>             <num> <num>         <num>  <int>      <int> <int>  <num>
   1:     2021-08-11  2021-09-08      1        1073       DE       00+    1073                 1     4    0.01863933      1          1     1   1073
   2:     2021-08-11  2021-09-08      1        1073       DE       00+    1073                 1     4    0.01863933      1          2     2   1073
   3:     2021-08-11  2021-09-08      1        1073       DE       00+    1073                 1     4    0.01863933      1          3     3   1073
   4:     2021-08-11  2021-09-08      1        1073       DE       00+    1073                 1     4    0.01863933      1          4     4   1073
   5:     2021-08-11  2021-09-08      1        1073       DE       00+    1073                 1     4    0.01863933      1          5     5   1073
  ---                                                                                                                                              
4996:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0    1.00000000      2        496   996   3965
4997:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0    1.00000000      2        497   997   4088
4998:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0    1.00000000      2        498   998   3227
4999:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0    1.00000000      2        499   999   3289
5000:     2021-09-08  2021-09-08      1        1487       DE       00+    1487                 1     0    1.00000000      2        500  1000   3982
```

**Other info**
Using `R` version 4.3.0 on macOS 14.5
`epinowcast` version 0.3.0

### PR DESCRIPTION
**Pull request by jessalynnsebastian**
## Description

This PR closes #473.

This PR corrects the postprocessing issues associated with using time steps other than days. It creates two helper functions, `subset_obs()` and `build_ord_obs()`, which wrap some repeated ode in `enw_nowcast_summary()` and `enw_nowcast_samples()`, and adds some basic documentation for them. It also adds tests for these functions using mock data with daily and weekly time steps.

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by seabbs** [comment]
This looks great so far. Just reading through now and will comment. 

Regarding the CI it looks like there is an issue unrelated to this PR (see https://github.com/epinowcast/epinowcast/issues/477)

File: R/postprocess.R [hunk 1]
```diff
@@ -403,3 +378,74 @@ enw_quantiles_to_long <- function(posterior) {
...
+#' @param sample String, "get_sample" or "no_sample".
+#' @param nowcast If getting posterior samples, the fit to pull
+#' the draws from.
+#'
+#' @return ord_obs A `data.table`.
+#'
+#' @family postprocess
+
+build_ord_obs <- function(obs, max_delay, timestep, sample, nowcast = NULL) {
+    internal_timestep <- get_internal_timestep(timestep)
```
Comment (seabbs) [inline R/postprocess.R:399]: as we still need this in the function that wraps this perhaps we should just pass in internal timestep?

File: R/postprocess.R [hunk 2]
```diff
@@ -403,3 +378,74 @@ enw_quantiles_to_long <- function(posterior) {
...
+  )
+  check_timestep_by_group(
+    ord_obs, "reference_date", timestep, exact = TRUE
+  )
+
+  ord_obs <- subset_obs(ord_obs, max_delay, internal_timestep,
+                        select = "after")
+
+  data.table::setorderv(ord_obs, c(".group", "reference_date"))
+  if (sample == "get_sample") {
```
Comment (seabbs) [inline R/postprocess.R:411]: or any character string inputs we should check them using `rlang::arg_match`. This would look like this.. 

```r
test <- function(test = c("option1", "option2")) {
	test <- rlang::arg_match(test)
}
```

File: R/postprocess.R (hunk 1 above)
Comment (jessalynnsebastian) [reply R/postprocess.R:399]: yeah you're right - felt wrong to pass in both timestep and internal timestep but it's cleaner

File: NEWS.md [hunk 3]
```diff
@@ -12,6 +12,8 @@
 
 ## Bugs
 
+- Fixed a bug where `enw_nowcast_summary()` and `enw_nowcast_samples()` incorrectly selected reference dates to include in their outputs when time steps were not days. See #473 by @jessalynnsebastian.
```
Comment (seabbs) [inline NEWS.md:15]:
```suggestion
- Fixed a bug where `enw_nowcast_summary()` and `enw_nowcast_samples()` incorrectly selected reference dates to include in their outputs when time steps were not days. See #473 by @jessalynnsebastian and reviewed by @seabbs.
```

File: R/postprocess.R [hunk 4]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+#'
+#' @param obs Observations as pulled from nowcast$latest[[1]].
+#' @param max_delay Whole number representing the maximum delay
+#' in units of the timestep.
+#' @param internal_timestep The internal timestep in days.
+#' @param timestep The timestep to be used. This can be a string
+#' ("day", "week", "month") or a numeric whole number representing
+#' the number of days.
+#' @param sample String, "get_sample" or "no_sample".
+#' @param nowcast If getting posterior samples, the fit to pull
```
Comment (seabbs) [inline R/postprocess.R:396]: I think this is actually a dataframe with a .draw column vs a fit (I think its the output of cmdstanr draws?)

File: R/postprocess.R [hunk 5]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+    ord_obs, "reference_date", timestep, exact = TRUE
+  )
+
+  ord_obs <- subset_obs(ord_obs, max_delay, internal_timestep,
+                        select = "after")
+
+sample <- rlang::arg_match(sample, c("get_sample", "no_sample"))
+
+  data.table::setorderv(ord_obs, c(".group", "reference_date"))
+  if (sample == "get_sample") {
```
Comment (seabbs) [inline R/postprocess.R:417]: this arg also needs a arg_match. Potentially we could just do this using the presence or absence of nowcast but perhaps that is a bit dangerous?

File: R/postprocess.R [hunk 6]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+    ord_obs <- ord_obs[order(.group, reference_date)]
+  }
+  return(ord_obs)
+}
+
+#' Subset observations data table for either modelled dates
+#' or not-modelled earlier dates.
+#'
+#' @param ord_obs The observations `data.table` to be subset,
+#' as pulled from the result of calling epinowcast() and
```
Comment (seabbs) [inline R/postprocess.R:432]:
```suggestion
#' as pulled from the result of calling [epinowcast()] and
```

(makes it a link in the rendered docs)

File: R/postprocess.R [hunk 7]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+#' coerced to a data table.
+#' @param max_delay Whole number representing the maximum delay
+#' in units of the timestep.
+#' @param internal_timestep A numeric value representing the number
+#' of days in the timestep, e.g. 7 when the timesteps are weeks.
+#' @param select String, select reference dates from "before" the
```
Comment (seabbs) [inline R/postprocess.R:438]: This is fine as is but if I was being really picky I might wonder if select was the best name to match what it does? Maybe `reference_from`?

File: R/postprocess.R [hunk 8]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+#' max_delay or "after"?
```
Comment (seabbs) [inline R/postprocess.R:439]: use back ticks (`) around arguments.

File: R/postprocess.R [hunk 9]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+#'
+#' @return A `data.frame` subset for the desired observations
+#'
+#' @family postprocess
+
+
+subset_obs <- function(ord_obs, max_delay, internal_timestep,
```
Comment (seabbs) [inline R/postprocess.R:446]: Uneven number of spaces between rogygen and the code (yes I know). In these cases just try and precisely match the package if there is a standard (its just about readings attention vs any implementation issues).

File: R/postprocess.R [hunk 10]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+                       select) {
+  select <- rlang::arg_match(select, c("before", "after"))
```
Comment (seabbs) [inline R/postprocess.R:448]: We might want to put `arg_match` in the roxygen i.e.

```
#` @inheritFrom rlang arg_match
```

File: R/postprocess.R [hunk 11]
```diff
@@ -403,3 +382,77 @@ enw_quantiles_to_long <- function(posterior) {
...
+  if (select == "after") {
+    return(ord_obs[reference_date > (max(reference_date, na.rm = TRUE) -
```
Comment (seabbs) [inline R/postprocess.R:450]: if we wanted to get fancy I assume we could do something fancy here with string composition and `eval` calls but it isn't needed here.

File: tests/testthat/test-subset_obs.R [hunk 12]
```diff
@@ -0,0 +1,93 @@
+# Daily data
+obs_daily <- enw_example("nowcast")$latest[[1]]
+# Mock weekly data
+obs_weekly <- data.table(
```
Comment (seabbs) [inline tests/testthat/test-subset_obs.R:4]: This is very handy - nice. We could move this to test/testhat/setup.R as its repeated and might be useful elsewhere?

File: tests/testthat/test-subset_obs.R [hunk 13]
```diff
@@ -0,0 +1,93 @@
...
+    max_delay * internal_timestep
+  result <- subset_obs(obs_daily, max_delay, internal_timestep,
+                       select = "after")
+  expect_true(all(result$reference_date > expected_cutoff))
+  expect_identical(unique(diff(result$reference_date)),
+                   as.integer(internal_timestep))
+})
+
+# Test 2: Select "before" (daily)
+test_that("select 'before' returns correct subset of reference dates when timesteps are days", { # nolint
```
Comment (seabbs) [inline tests/testthat/test-subset_obs.R:29]: I usually put the function name at the beginning of the test string. - not sure if it really matters but may as well follow that pattern unless a reason not to?

**Review by seabbs — COMMENTED** [review]
This all looks really great and functionality wise I am happy. Some nit picks about style and things and need to resolve the CI bug (on it tomorrow) so we can get a better understanding of if anything else is impacted but this. 

Nice stuff!

**Comment by seabbs** [comment]
Looking at the raw CI output the only potential issue I see related to this work is the following: 

>   Missing link or links in Rd file 'build_ord_obs.Rd':
>    ‘1’
>  
>  See section 'Cross-references' in the 'Writing R Extensions' manual.

File: R/postprocess.R (hunk 5 above)
Comment (jessalynnsebastian) [reply R/postprocess.R:417]: My preference is to do it that way, checking for presence of `nowcast` but wasn't sure if it would be a bad idea. Do you have strong opinions one way or the other?

File: R/postprocess.R (hunk 11 above)
Comment (jessalynnsebastian) [reply R/postprocess.R:450]: It seems like i might be able to do something pretty easily with `match.fun()`. I like that better than what I have, might give it a go

File: R/postprocess.R (hunk 5 above)
Comment (seabbs) [reply R/postprocess.R:417]: No I don't. If this was a user facing function and I thought they would be very confused by the auto-magical difference you get from passing a data frame I might push for the second name. We could meet in the middle somewhere and rename this to be a bit more generic but a bit clearer about what happens internally (precisely what a short name that communicates that is is currently a bit beyond me).

File: R/postprocess.R (hunk 7 above)
Comment (jessalynnsebastian) [reply R/postprocess.R]: Now that I'm making the argument the inequality itself, I still don't feel like I have a good name. Have it as reference_subset for now

File: R/postprocess.R (hunk 5 above)
Comment (jessalynnsebastian) [reply R/postprocess.R]: Modified the function to this but didn't yet come up with a good name. hard to convey concisely, will think on it

**Comment by jessalynnsebastian** [comment]
> Looking at the raw CI output the only potential issue I see related to this work is the following:
> 
> > Missing link or links in Rd file 'build_ord_obs.Rd':
> > ‘1’
> > See section 'Cross-references' in the 'Writing R Extensions' manual.

@seabbs Actually saw this when I ran the devtools check and meant to ask for your assistance. I don't really understand what's going on because I thought I wrote the docs essentially the same way for the two functions, so I don't know why one of the Rd files roxygen generates would be problematic but the other not. Didn't see anything immediately helpful in that R extensions manual

File: R/postprocess.R (hunk 7 above)
Comment (seabbs) [reply R/postprocess.R]: Yeah me neither. That seems like a good enough choice unless inspiration strikes.

File: man/build_ord_obs.Rd [hunk 14]
```diff
@@ -0,0 +1,42 @@
+% Generated by roxygen2: do not edit by hand
+% Please edit documentation in R/postprocess.R
+\name{build_ord_obs}
+\alias{build_ord_obs}
+\title{Build the ord_obs \code{data.table}.}
+\usage{
+build_ord_obs(obs, max_delay, internal_timestep, timestep, nowcast = NULL)
+}
+\arguments{
+\item{obs}{Observations as pulled from nowcast$latest[\link{1}].}
```
Comment (seabbs) [inline man/build_ord_obs.Rd:10]: I think this is the link problem (will go and read the non md but my expectation is that this code is missing back ticks. I would be interested to know if your LLM of choice could have caught this (because language style is something they are good at and the human eye is not)

Comment (seabbs) [reply man/build_ord_obs.Rd:10]: update after reading the raw roxygen and yes I think this is the problem

**Comment by seabbs** [comment]
Noting as per the contributing guide before we merge this you cna/should add yourself here https://github.com/epinowcast/epinowcast/blob/d957b21af07c7708d8ae28fc248fffe39d453828/DESCRIPTION#L80 as a contributor.

**Comment by jessalynnsebastian** [comment]
@seabbs When you get the chance, take a look at checking for the presence of `nowcast` to decide whether to sample in `build_ord_obs()` and my usage of `match.fun()` in `subset_obs()`? Tests are still passing, and now that the doc issue is fixed, that warning is gone from the devtools check. Think we're close to being good to go.

**Comment by jessalynnsebastian** [comment]
Below is what the call to `epinowcast::plot()` currently looks like when applied to the Germany weekly data: 

germany_weekly_old


And here is what it looks like using the functions updated in this PR:

germany_weekly_new

File: tests/testthat/setup.R [hunk 15]
```diff
@@ -25,3 +25,16 @@ if (on_ci() && Sys.info()["sysname"] == "Linux" && not_on_cran()) {
...
+# build_ord_obs())
+obs_weekly <- data.table(
+    reference_date = as.IDate("2021-07-28") + 7 * (0:6),
+    report_date = c(as.IDate("2021-08-25") + 7 * (0:2),
+                    rep(as.IDate("2021-09-08"), 4)),
+    .group = rep(1, times = 7),
+    max_confirm = c(625, 856, 1073, 1733, 2268, 2388, 1487),
+    confirm = c(615, 847, 1073, 1733, 2268, 2388, 1487),
+    cum_prop_reported = c(615 / 625, 847 / 856, rep(1, 5)),
+    delay = c(rep(4, 3), 3:0)
```
Comment (seabbs) [inline tests/testthat/setup.R:39]: Lint warning here

**Review by seabbs — COMMENTED** [review]
Yes I agree (I switched this away from being a draft). I think this all looks good and am happy. One linting note and I still need to fix the CI. Will do that and circle back here 🥳

**Review by seabbs — APPROVED** [review]
Nice this all looks good to me!
