### PR TITLE
Issue 378: Use lintr::lint_package() and resolve all issues found package wide

### LINKED ISSUE #378: Use == to match length-1 scalars, not %in%. Note that == preserves NA where %in% does not.
**Describe the bug**
Linting is currently an issue due to a new check. Linting issues should be resolved after a local linting check.

**To Reproduce**
Run `lintr`

**Expected behavior**
No warnings or errors from `lintr`

### PR DESCRIPTION
**Pull request by seabbs**
## Description

This PR closes #378.

This PR just makes changes in order to get `lintr::lint_package()` to pass without any listing issues. I have opened a new issue to help us prevent this from happening again (#383). This is a blocker for #376 as well as future PRs if we wish their CI to pass without introducing spurious changes.

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/epinowcast/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [x] I have updated the package development version by one increment in both `NEWS.md` and the `DESCRIPTION`.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

File: R/check.R [hunk 1]
```diff
@@ -309,13 +309,13 @@ check_numeric_timestep <- function(dates, date_var, timestep, exact = TRUE) {
     check <- sum(diffs %% timestep) == 0
   }
 
-  if (!check) {
+  if (check) {
+    return(invisible(NULL))
+  }else {
```
Comment (pearsonca) [inline R/check.R:314]:
```suggestion
  } else {
```

Comment (pearsonca) [reply R/check.R:314]: the linter must complain about that, yeah?

File: R/epinowcast.R [hunk 2]
```diff
@@ -162,12 +162,12 @@ epinowcast <- function(data,
...
+  if (!missing$formula == "~0") {
     warning("The missing data model is highly experimental. There is a
      significant likelihood that bugs are present in its implementation.")
   }
 
-  if (!missing$formula %in% "~0") {
+  if (!missing$formula == "~0") {
     warning("The missing data model is highly experimental. There is a
      significant likelihood that bugs are present in its implementation.")
   }
```
Comment (pearsonca) [inline R/epinowcast.R:173]: this seems oddly repetitive - am I missing something?

**Review by pearsonca — COMMENTED** [review]
Looks good overall. One space I'm surprised linter didn't catch, one odd bit of code, but maybe I'm miss reading something.

File: R/data-converters.R [hunk 3]
```diff
@@ -348,13 +348,13 @@ enw_incidence_to_cumulative <- function(obs, by = NULL) {
...
 #' @examples
-#' nat_hosp <- germany_covid19_hosp[location == "DE"][age_group %in% "00+"]
+#' nat_hosp <- germany_covid19_hosp[location == "DE"][age_group == "00+"]
 #' enw_aggregate_cumulative(nat_hosp, timestep = "week")
 enw_aggregate_cumulative <- function(
   obs, timestep = "day", by = NULL,
   min_reference_date = min(obs$reference_date, na.rm = TRUE), copy = TRUE
 ) {
-  stopifnot("The data already has a timestep of a day" = !timestep %in% "day")
+  stopifnot("The data already has a timestep of a day" = !timestep == "day")
```
Comment (Bisaloo) [inline R/data-converters.R:357]:
```suggestion
  stopifnot("The data already has a timestep of a day" = timestep != "day")
```

There is a linter coming for this some it might be worth getting ahead of it here?

File: R/epinowcast.R [hunk 4]
```diff
@@ -162,12 +162,12 @@ epinowcast <- function(data,
     enw_priors_as_data_list(priors)
   )
 
-  if (!missing$formula %in% "~0") {
+  if (!missing$formula == "~0") {
```
Comment (Bisaloo) [inline R/epinowcast.R:165]:
```suggestion
  if (missing$formula != "~0") {
```

File: R/epinowcast.R [hunk 5]
```diff
@@ -162,12 +162,12 @@ epinowcast <- function(data,
...
     warning("The missing data model is highly experimental. There is a
      significant likelihood that bugs are present in its implementation.")
   }
 
-  if (!missing$formula %in% "~0") {
+  if (!missing$formula == "~0") {
```
Comment (Bisaloo) [inline R/epinowcast.R:170]:
```suggestion
  if (missing$formula != "~0") {
```

File: R/model-modules.R [hunk 6]
```diff
@@ -251,7 +251,7 @@ enw_report <- function(non_parametric = ~0, structural = ~0, data) {
   )
   data_list$rep_t <- data$time[[1]] + data$max_delay[[1]] - 1
   data_list$model_rep <- as.numeric(
-    !as_string_formula(non_parametric) %in% "~1"
+    !as_string_formula(non_parametric) == "~1"
```
Comment (Bisaloo) [inline R/model-modules.R:254]:
```suggestion
    as_string_formula(non_parametric) != "~1"
```

File: R/model-modules.R [hunk 7]
```diff
@@ -512,12 +512,12 @@ enw_expectation <- function(r = ~ 0 + (1 | day:.group), generation_time = 1,
 #' enw_missing(~0, data = enw_example("preprocessed"))
 enw_missing <- function(formula = ~1, data) {
   if (nrow(data$missing_reference[[1]]) == 0 &&
-    !(as_string_formula(formula) %in% "~0")) {
+    !(as_string_formula(formula) == "~0")) {
```
Comment (Bisaloo) [inline R/model-modules.R:515]:
```suggestion
    as_string_formula(formula) != "~0") {
```

**Review by Bisaloo — COMMENTED** [review]
I've made suggestions for this but a better way to write `!x %in% "a"` is `x != "a" rather than `!x == "a"`.

The next lintr version will have a lintr for this so it's probably worth using the better version already?

File: R/epinowcast.R (hunk 2 above)
Comment (seabbs) [reply R/epinowcast.R]: Yes, this is a duplication and no I don't know why it is in there!

File: R/check.R (hunk 1 above)
Comment (seabbs) [reply R/check.R]: Oddly no it doesn't but I have fixed.

**Comment by seabbs** [comment]
Thanks for the good reviews both. I've added you both to the news item (I also cheekily updated the overall contributors list as it had got a little out of date and added a space).

> but a better way to write

Thanks for this @Bisaloo (me being lazy here). I have no idea if your suggestion will work with switch - I guess we will see.

@pearsonca its not clear to me why `lintr` didn't flag the lack of space ahead of `else` but I've updated.

**Review by pearsonca — APPROVED** [review]
