### PR TITLE
Issue 333: Support fitting models where the max delay is longer than the empirical delay

### LINKED ISSUE #333: epinowcast should support using less data than the max Delay or fail informatively
**Describe the bug**
I'm running nowcasts every week on last year's US flu data. I would like the model to have a max delay of 12 weeks for all nowcasts across the season. Early on in the season, there is less than 12 weeks worth of data. After running `enw_preprocess_data(data, max_delay=12, timestep="week")`, and passing that into `epinowcast()`, I get a stan error:
```
Chain 1 Exception: mismatch in dimension declared and found in context; 
processing stage=data initialization; 
variable name=obs; position=1; 
dims declared=(4,12); dims found=(4,4)
```

**Expected behavior**
`enw_preprocess_data()` would set the correct dimensions for stan _or provide a meaningful error message_.

### PR DESCRIPTION
**Pull request by seabbs**
## Description

This PR closes #333.

As discussed in #333 this issue enables users to fit models where the empirical delay (i.e. the delay that is observed in the data) is shorter than the max delay. This is useful at the beginning of outbreaks and when surveillance is seasonal. However, it can be dangerous and needs to be used with care (see the doc updates around this). 

This PR is related to #204 and takes a different approach to dealing with the issue. @adrian-lison we should discuss to see which direction we want to go and want things are cross-compatible. 

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/epinowcast/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [x] I have added a news item linked to this PR.
- [ ] I have updated the package development version by one increment in both `NEWS.md` and the `DESCRIPTION`.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

File: tests/testthat/test-epinowcast.R [hunk 1]
```diff
@@ -94,7 +94,42 @@ test_that("epinowcast can fit a simple reporting model", {
...
+    enw_preprocess_data(max_delay = 30)
+  )
+
+  nowcast <- suppressMessages(epinowcast(pobs_long_delay,
+    fit = enw_fit_opts(
+      sampler = silent_enw_sample,
+      save_warmup = FALSE, pp = FALSE,
+      chains = 2, iter_warmup = 250, iter_sampling = 500,
+      refresh = 0, show_messages = FALSE
+    ),
```
Comment (adrian-lison) [inline tests/testthat/test-epinowcast.R:113]: I get a few divergent transitions with this example, but I guess in part this is also because we use a short warmup here...

**Review by adrian-lison — APPROVED** [review]
I think this is definitely also a valuable option. Since this is the more dangerous approach in my opinion, I would say it makes most sense to have #224 as the default and tell the user in the warning that they can also switch to extrapolation (for example via an additional argument in `enw_obs`).

Until #224 is solved, I added a short warning to `enw_obs` to make the user aware of the extrapolation going on...

**Comment by adrian-lison** [comment]
> This is how benchmark results would change (along with a 95% confidence interval in relative change) if [8eff560](https://github.com/epinowcast/epinowcast/commit/8eff560d1fd8305f5fb26c21324b2bfca1f002b4) is merged into main:
> 
>     * 🚀day_of_week_model: 54.7s -> 36.1s [-42.05%, -25.8%]
> 
>     * 🚀latent_renewal_model: 57.9s -> 41.4s [-48.28%, -8.54%]
> 
>     * 🚀missingness_model: 1.96m -> 1.89m [-6.53%, -0.53%]
> 
>     * 🚀multi_group_latent_renewal_model: 12.9s -> 10.4s [-29.83%, -9.19%]
> 
>     * ☑️preprocessing: 956ms -> 959ms [-0.78%, +1.43%]
> 
>     * 🚀simple_model: 18.8s -> 8s [-91.13%, -23.8%]
> 
>     * ☑️simple_negbin_model_with_pp: 8.87s -> 7.06s [-48.15%, +7.43%]
>       These benchmarks are based on package examples which are available [here](https://github.com/epinowcast/epinowcast/tree/main/inst/examples). Further explanation regarding interpretation and methodology can be found in the [documentation of `touchstone`](https://lorenzwalthert.github.io/touchstone/articles/inference.html).

Why is this so much faster than in `main`?

File: tests/testthat/test-epinowcast.R (hunk 1 above)
Comment (seabbs) [reply tests/testthat/test-epinowcast.R:113]: Yeah it really isn't ideal. I've opened an issue to go through and try and identify performance bottlenecks with the examples #350 which hopefully should help improve this.

File: inst/stan/epinowcast.stan [hunk 2]
```diff
@@ -216,7 +215,7 @@ transformed parameters{
   vector[refp_fnrow] refp_sd;
   matrix[dmax, refp_fnrow] refp_lh; // sparse report logit hazards
   // Non-parametric reference model
-  vector[refnp_fnindex] refnp_lh; 
+  vector[model_refnp > 0 ? refnp_fnindex : 0] refnp_lh;
```
[the remark this answers is not in the document]
Comment (seabbs) [reply inst/stan/epinowcast.stan:218]: Yes exactly. Bad practice from me on putting this in here!

File: inst/stan/epinowcast.stan [hunk 3]
```diff
@@ -38,7 +38,6 @@ data {
   array[s] int csdmax; // cumulative version of sdmax
  
   // Observations
-  array[s, dmax] int obs; // obs by reference date (row) and delay (column)
```
[the remark this answers is not in the document]
Comment (seabbs) [reply inst/stan/epinowcast.stan:41]: Yup (can put in its own PR?)

**Comment by seabbs** [comment]
> Why is this so much faster than in

I am really not sure unless the presence of the `refnp_lh` was slowing things down? 

After talking I think the plan is to move forwards with this PR and update #224 to not automatically update the max delay. I think we should stick with including warnings about extrapolation though.

File: NEWS.md [hunk 4]
```diff
@@ -20,7 +20,6 @@ This release is in development and not yet ready for production use.
 
 ## Package
 
-- Fixed some typos in `single-timeseries-rt-estimation.Rmd`. The `WORDLIST` used by spelling has also been updated to eliminate false positives. Future typos will now generate an error in the continuous integration check so that we can catch them as early as possible. See #341 by @Bisaloo and reviewed by @seabbs.
```
Comment (seabbs) [inline NEWS.md:23]: why are we removing this? Is it a duplicate?

Comment (adrian-lison) [reply NEWS.md:23]: You tell me :D
https://github.com/epinowcast/epinowcast/commit/f8e929140b51aa67e8d9b230fc6b26c9024e819c

**Review by adrian-lison — DISMISSED** [review]
Let's go? (After the news item is added back in?)

File: NEWS.md (hunk 4 above)
Comment (seabbs) [reply NEWS.md:23]: Weird!

**Review by adrian-lison — APPROVED** [review]

**Comment by seabbs** [comment]
Ubuntu-based actions are failing because of #360. Going to go ahead and merge this and monitor CI over the next few days.
